export const githubActionTypes = {
  GITHUB_SEARCH: 'GITHUB_SEARCH',
  CLEAR_GITHUB_SEARCH_PAGE: 'CLEAR_GITHUB_SEARCH_PAGE',
};

export const cacheActionTypes = {
  CACHE_GITHUB_SEARCH: 'CACHE_GITHUB_SEARCH',
  CLEAR_GITHUB_SEARCH_CACHE: 'CLEAR_GITHUB_SEARCH_CACHE',
};
